FROM openjdk:jre-alpine

ADD target/acmeair-flightservice-java-thorntail.jar /opt/thorntail.jar

ENV JAEGER_SERVICE_NAME=jaeger-service
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=false
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/opt/thorntail.jar", "-Djava.net.preferIPv4Stack=true"]
